site_name: BTstack Arduino Manual
site_dir: btstack-arduino
pages:
- [index.md, Welcome]
- [tutorial.md, Quick Start]
- [examples/intro.md, Examples]
- [examples/generated.md, List of Examples]
theme: readthedocs
