site_name: BTstack Manual
site_dir: btstack
docs_dir: docs_final
pages:
- [index.md, Welcome]
- [quick_start.md, Quick Start]
- [architecture.md, BTstack Architecture]
- [how_to.md, How to use BTstack]
- [protocols.md, Supported Protocols]
- [profiles.md, Supported Profiles]
- [examples/examples.md, Embedded Examples]
- [porting.md, Porting to Other Platforms]
- [integration.md, Integrating with Existing Systems]
- [appendix/apis.md, APIs]
- [appendix/events_errors.md, Events and Errors]
theme: readthedocs