site_name: BTstack Manual v1.0
site_dir: btstack
docs_dir: docs_final
pages:
- [index.md, Welcome]
- [quick_start.md, Quick Start]
- [architecture.md, BTstack Architecture]
- [how_to.md, How to configure BTstack]
- [protocols.md, Supported Protocols]
- [profiles.md, Supported Profiles]
- [examples/examples.md, Embedded Examples]
- [porting.md, Porting to Other Platforms]
- [integration.md, Integrating with Existing Systems]
- [appendix/apis.md, APIs]
- [appendix/events_errors.md, Events and Errors]
- [appendix/migration.md, Migration to v1.0]
theme: readthedocs
