site_name: BTstack Manual
site_dir: btstack
pages:
- [index.md, Welcome]
- [quick_start.md, Quick Start]
- [architecture.md, BTstack Architecture]
- [how_to.md, How to use BTstack]
- [protocols.md, Protocols]
- [profiles.md, Profiles]
- [examples/generated.md, Examples]
- [porting.md, Porting]
- [integration.md, Integrating with Existing Systems]
- [appendix/apis.md, APIs]
- [appendix/events_errors.md, Events and Errors]
theme: readthedocs